"""Embed editable Python sources without platform string-literal size limits."""

import argparse
import hashlib
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path)
    parser.add_argument("--module", nargs=2, action="append", default=[], metavar=("SYMBOL", "PATH"))
    parser.add_argument("--hash-file", type=Path, action="append", default=[])
    args = parser.parse_args()
    digest = hashlib.sha256()
    chunks = ["/* Generated by python/embed.py. Do not edit. */\n#pragma once\n"]
    for symbol, filename in args.module:
        if not symbol.isidentifier() or not symbol.isascii():
            parser.error(f"Invalid C identifier: {symbol}")
        source = Path(filename).read_bytes()
        compile(source, filename, "exec")
        if b"\0" in source:
            parser.error(f"Embedded source contains NUL: {filename}")
        digest.update(symbol.encode("ascii") + b"\0" + source + b"\0")
        data = source + b"\0"
        chunks.append(f"static const char {symbol}[] = {{\n")
        for offset in range(0, len(data), 24):
            chunks.append("    " + ",".join(str(value) for value in data[offset:offset + 24]) + ",\n")
        chunks.append("};\n")
    for filename in args.hash_file:
        digest.update(filename.read_bytes() + b"\0")
    chunks.append(f'#define SOURCE_FILE_SHA256_HASH "{digest.hexdigest()}"\n')
    content = "".join(chunks)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    if not args.output.exists() or args.output.read_text(encoding="utf-8") != content:
        args.output.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
