/* Inline x86-64 detour engine for hooking `@:hlNative` functions.
 *
 * HL bytecode functions are hookable because their JIT-compiled bodies carry
 * an injected prologue check (jit_hook_call). Natives have no such body:
 * they are raw dlsym'd C pointers, and every caller bakes the resolved
 * address in as an immediate constant at JIT-compile time (see
 * op_call_fun's native branch in jit.c). Patching functions_ptrs[findex]
 * after the fact does nothing for callers already compiled, so the only way
 * to intercept an already-running native is to redirect its own machine code
 * at the address every caller already has. This file does exactly that:
 * a conservative length disassembler finds a safe prologue to overwrite, a
 * copy of the overwritten bytes plus a jump back becomes the "call original"
 * path, and the landing stub is generated by hl_jit_native_hook_adapter
 * (jit.c), which reuses the same dispatch (jit_dispatch_hook) and Python
 * hook chain (modcore._hooks) already used for bytecode functions.
 *
 * Deliberately narrow and fails loudly: if the length disassembler cannot
 * confidently account for at least 12 bytes of linear, non-branching
 * instructions at the native's entry point, hooking is refused with a clear
 * Python exception rather than guessing at an instruction boundary. Only
 * x86-64 targets are supported, matching the only architectures hlmod-hl's
 * JIT itself targets. */

#include "native_hook.h"
#include <string.h>
#include <stdint.h>
#include <stdio.h>

#if defined(HL_WIN)
/* hl.h's own _GUID macro (a native type-signature string constant) collides
 * textually with windows.h's `typedef struct _GUID { ... } GUID;` - the same
 * workaround already used in gc.c/module.c/random.c/sys.c. */
#undef _GUID
#include <windows.h>
#else
#include <sys/mman.h>
#include <unistd.h>
#endif

typedef struct InstalledNativeHook {
    int findex;
    void *landing;
    UT_hash_handle hh;
} InstalledNativeHook;

static InstalledNativeHook *g_installed_native_hooks = NULL;

#if defined(HL_64) && !defined(HL_CONSOLE)

/* Length, in bytes, of a ModRM (+SIB +disp) sequence starting at `p`. Always
 * succeeds: every byte value is a well-formed ModRM byte. */
static int modrm_len(const unsigned char *p) {
    unsigned char modrm = p[0];
    int mod = (modrm >> 6) & 3;
    int rm = modrm & 7;
    int len = 1;
    if (mod == 3) return len;
    if (rm == 4) {
        unsigned char sib = p[1];
        int base = sib & 7;
        len += 1;
        if (mod == 0 && base == 5) len += 4; /* disp32, no base */
    } else if (mod == 0 && rm == 5) {
        len += 4; /* RIP-relative disp32 */
    }
    if (mod == 1) len += 1;
    else if (mod == 2) len += 4;
    return len;
}

/* Decodes exactly one x86-64 instruction at `code`. Returns 1 and fills
 * `*out_len` (and `*is_terminal` for control-flow instructions) on success,
 * or 0 if the encoding is outside the narrow set this decoder recognizes.
 * Only common compiler-emitted prologue instructions are accepted; anything
 * else is treated as unrecognized rather than guessed at. */
static int decode_one(const unsigned char *code, int *out_len, int *is_terminal, bool *is_call_reloc) {
    int i = 0;
    int rex_w = 0;
    *is_terminal = 0;
    *is_call_reloc = false;

    if (code[0] == 0xF3 && code[1] == 0x0F && code[2] == 0x1E && code[3] == 0xFA) {
        *out_len = 4; /* endbr64 */
        return 1;
    }

    while (1) {
        unsigned char b = code[i];
        if (b == 0x66 || b == 0x67 || b == 0x2E || b == 0x36 || b == 0x3E ||
            b == 0x26 || b == 0x64 || b == 0x65 || b == 0xF0 || b == 0xF2 || b == 0xF3) {
            i++;
            continue;
        }
        break;
    }
    if ((code[i] & 0xF0) == 0x40) {
        rex_w = (code[i] & 0x08) != 0;
        i++;
    }

    unsigned char op = code[i];
    switch (op) {
    case 0x50: case 0x51: case 0x52: case 0x53:
    case 0x54: case 0x55: case 0x56: case 0x57:
    case 0x58: case 0x59: case 0x5A: case 0x5B:
    case 0x5C: case 0x5D: case 0x5E: case 0x5F:
    case 0x90:
        *out_len = i + 1;
        return 1;
    case 0xC3:
        *out_len = i + 1;
        *is_terminal = 1;
        return 1;
    case 0xC2:
        *out_len = i + 3;
        *is_terminal = 1;
        return 1;
    /* `call rel32` always returns control to the very next byte, so unlike
     * every other control-flow instruction here it's safe to keep decoding
     * past it - but only after fixing up its displacement for its new
     * address, since rel32 is relative to the instruction's own location.
     * `jmp rel32` never returns, so it stays an unrelocated hard stop: its
     * target is arbitrary and may not be the trampoline's own resume point. */
    case 0xE8:
        *out_len = i + 5;
        *is_call_reloc = true;
        return 1;
    case 0xE9:
        *out_len = i + 5;
        *is_terminal = 1;
        return 1;
    case 0xEB:
        *out_len = i + 2;
        *is_terminal = 1;
        return 1;
    case 0x6A:
        *out_len = i + 2;
        return 1;
    case 0x68:
        *out_len = i + 5;
        return 1;
    case 0xB0: case 0xB1: case 0xB2: case 0xB3:
    case 0xB4: case 0xB5: case 0xB6: case 0xB7:
        *out_len = i + 2;
        return 1;
    case 0xB8: case 0xB9: case 0xBA: case 0xBB:
    case 0xBC: case 0xBD: case 0xBE: case 0xBF:
        *out_len = i + 1 + (rex_w ? 8 : 4);
        return 1;
    case 0x70: case 0x71: case 0x72: case 0x73: case 0x74: case 0x75:
    case 0x76: case 0x77: case 0x78: case 0x79: case 0x7A: case 0x7B:
    case 0x7C: case 0x7D: case 0x7E: case 0x7F:
        *out_len = i + 2;
        *is_terminal = 1;
        return 1;
    case 0x0F: {
        unsigned char op2 = code[i + 1];
        if (op2 >= 0x80 && op2 <= 0x8F) {
            *out_len = i + 6;
            *is_terminal = 1;
            return 1;
        }
        if (op2 == 0x1F || op2 == 0xB6 || op2 == 0xB7 || op2 == 0xBE || op2 == 0xBF || op2 == 0xAF ||
            op2 == 0x10 || op2 == 0x11 || op2 == 0x28 || op2 == 0x29 || op2 == 0x6F || op2 == 0x7F) {
            *out_len = i + 2 + modrm_len(code + i + 2);
            return 1;
        }
        return 0;
    }
    case 0x00: case 0x01: case 0x02: case 0x03:
    case 0x08: case 0x09: case 0x0A: case 0x0B:
    case 0x10: case 0x11: case 0x12: case 0x13:
    case 0x18: case 0x19: case 0x1A: case 0x1B:
    case 0x20: case 0x21: case 0x22: case 0x23:
    case 0x28: case 0x29: case 0x2A: case 0x2B:
    case 0x30: case 0x31: case 0x32: case 0x33:
    case 0x38: case 0x39: case 0x3A: case 0x3B:
    case 0x84: case 0x85: case 0x86: case 0x87:
    case 0x88: case 0x89: case 0x8A: case 0x8B:
    case 0x8D:
        *out_len = i + 1 + modrm_len(code + i + 1);
        return 1;
    case 0x69:
        *out_len = i + 1 + modrm_len(code + i + 1) + 4;
        return 1;
    case 0x6B:
        *out_len = i + 1 + modrm_len(code + i + 1) + 1;
        return 1;
    case 0x80:
    case 0x83:
    case 0xC6:
        *out_len = i + 1 + modrm_len(code + i + 1) + 1;
        return 1;
    case 0x81:
    case 0xC7:
        *out_len = i + 1 + modrm_len(code + i + 1) + 4;
        return 1;
    case 0xFF: {
        unsigned char modrm = code[i + 1];
        int reg = (modrm >> 3) & 7;
        *out_len = i + 1 + modrm_len(code + i + 1);
        if (reg >= 2 && reg <= 5) *is_terminal = 1; /* call/jmp (near/far) */
        return 1;
    }
    default:
        return 0;
    }
}

#define HLMOD_MAX_RELOCATIONS 4

/* Walks instructions from `code` until at least `min_len` bytes have been
 * accounted for, refusing (returns -1) on any unrecognized encoding or any
 * unrelocatable control-flow instruction reached before that point.
 * Records the offset of every `call rel32` found (it will need its
 * displacement fixed up once copied to a new address) into `reloc_offsets`,
 * up to `max_relocs` entries; refuses rather than silently dropping one if
 * there are more than that. */
static int safe_prologue_len_ex(const unsigned char *code, int min_len, int *reloc_offsets, int max_relocs, int *reloc_count) {
    int offset = 0;
    *reloc_count = 0;
    while (offset < min_len) {
        int len = 0, terminal = 0;
        bool call_reloc = false;
        if (!decode_one(code + offset, &len, &terminal, &call_reloc) || len <= 0) return -1;
        if (terminal) return -1;
        if (call_reloc) {
            if (*reloc_count >= max_relocs) return -1;
            reloc_offsets[(*reloc_count)++] = offset;
        }
        offset += len;
        if (offset > min_len + 16) return -1; /* runaway guard */
    }
    return offset;
}

static int safe_prologue_len(const unsigned char *code, int min_len) {
    int reloc_offsets[HLMOD_MAX_RELOCATIONS], reloc_count = 0;
    return safe_prologue_len_ex(code, min_len, reloc_offsets, HLMOD_MAX_RELOCATIONS, &reloc_count);
}

#define HLMOD_JUMP_SIZE 14

/* `jmp qword ptr [rip+0]` followed by the absolute target as an inline
 * 8-byte operand. Unlike a `mov reg,imm64; jmp reg` sequence, this clobbers
 * no general-purpose register, which matters for the resume trampoline: the
 * copied prologue bytes immediately before it may have left a live value in
 * any register (e.g. a `lea rax, [...]` feeding a later `mov rdi, rax`), and
 * clobbering it there would corrupt the resumed function's own logic. */
static void write_jump(unsigned char *at, void *target) {
    at[0] = 0xFF;
    at[1] = 0x25;
    at[2] = 0;
    at[3] = 0;
    at[4] = 0;
    at[5] = 0;
    memcpy(at + 6, &target, 8);
}

#if defined(HL_WIN)
/* x86-64 SEH requires every non-leaf function - one whose frame could be a
 * return address sitting on the stack when an exception is dispatched - to
 * carry unwind metadata describing how to restore the caller's registers.
 * Code the OS itself never linked, like the landing stub
 * hl_jit_native_hook_adapter (jit.c) builds at runtime, carries none by
 * default. The moment any exception needs to unwind *through* such a frame
 * - a real hardware fault surfacing deeper in a hook callback, for example
 * - `RtlDispatchException` can't compute how to walk past it, and the
 * whole process is torn down immediately with STATUS_BAD_FUNCTION_TABLE,
 * bypassing even hlmod's own top-level SEH filter (hlmod_setup_handler)
 * entirely. This was reproduced on real Windows CI hardware (Wine's own
 * unwinder is far more lenient about missing tables and let it slide).
 *
 * The landing stub's prologue is fixed and known: `push rbp; mov rbp, rsp`
 * (see hl_jit_native_hook_adapter), exactly the shape x64 unwind info
 * describes via UWOP_SET_FPREG. Once the frame register is pinned to rbp,
 * the unwinder only needs that one fact to walk past this frame correctly
 * - whatever it does afterwards (further pushes, `sub rsp`, calls) is
 * irrelevant to unwinding once a frame pointer is established, so this
 * minimal, hand-built UNWIND_INFO stays correct regardless of how the rest
 * of that stub's code generation evolves. */
#pragma pack(push, 1)
typedef struct HlmodUnwindInfo {
    unsigned char VersionAndFlags;      /* version 1, flags 0 (UNW_FLAG_NHANDLER) */
    unsigned char SizeOfProlog;         /* `push rbp` (1) + `mov rbp,rsp` (3) = 4 */
    unsigned char CountOfCodes;
    unsigned char FrameRegisterAndOffset; /* rbp, offset 0 */
    unsigned char CodeOffset0;          /* codes stored in reverse execution order */
    unsigned char UnwindOpAndInfo0;     /* UWOP_SET_FPREG @ offset 4 */
    unsigned char CodeOffset1;
    unsigned char UnwindOpAndInfo1;     /* UWOP_PUSH_NONVOL(rbp) @ offset 1 */
} HlmodUnwindInfo;
#pragma pack(pop)

typedef struct HlmodUnwindBlob {
    HlmodUnwindInfo info;
    RUNTIME_FUNCTION fn;
} HlmodUnwindBlob;

#define HLMOD_UWOP_PUSH_NONVOL 0
#define HLMOD_UWOP_SET_FPREG   3
#define HLMOD_REG_RBP          5

/* Registers unwind info for a landing stub allocated at `code`/`codesize`
 * (the buffer hl_alloc_executable_memory returned for it). `codesize` is
 * always page-rounded (see hl_jit_native_hook_adapter) while the real
 * instructions are a few dozen bytes at most, leaving plenty of room to
 * tuck the metadata away in the same page without a second allocation. */
static void register_landing_unwind_info(void *code, int codesize) {
    size_t blob_off = ((size_t)codesize - sizeof(HlmodUnwindBlob)) & ~(size_t)3;
    HlmodUnwindBlob *blob = (HlmodUnwindBlob *)((unsigned char *)code + blob_off);
    blob->info.VersionAndFlags = 1;
    blob->info.SizeOfProlog = 4;
    blob->info.CountOfCodes = 2;
    blob->info.FrameRegisterAndOffset = HLMOD_REG_RBP;
    blob->info.CodeOffset0 = 4;
    blob->info.UnwindOpAndInfo0 = HLMOD_UWOP_SET_FPREG;
    blob->info.CodeOffset1 = 1;
    blob->info.UnwindOpAndInfo1 = (unsigned char)(HLMOD_UWOP_PUSH_NONVOL | (HLMOD_REG_RBP << 4));
    blob->fn.BeginAddress = 0;
    blob->fn.EndAddress = (DWORD)codesize;
    blob->fn.UnwindData = (DWORD)blob_off;
    BOOLEAN added = RtlAddFunctionTable(&blob->fn, 1, (DWORD64)(uintptr_t)code);
    DWORD64 imagebase = 0;
    PRUNTIME_FUNCTION found = RtlLookupFunctionEntry((DWORD64)(uintptr_t)code, &imagebase, NULL);
    fprintf(stderr, "HLMOD_DEBUG unwind: added=%d found=%p imagebase=0x%llX code=%p blob_off=%zu\n",
        (int)added, (void *)found, (unsigned long long)imagebase, code, blob_off);
    fflush(stderr);
}
#endif

#if defined(HL_WIN)
static int patch_target(void *target, void *landing) {
    DWORD old;
    if (!VirtualProtect(target, HLMOD_JUMP_SIZE, PAGE_EXECUTE_READWRITE, &old)) return -1;
    write_jump((unsigned char *)target, landing);
    VirtualProtect(target, HLMOD_JUMP_SIZE, old, &old);
    FlushInstructionCache(GetCurrentProcess(), target, HLMOD_JUMP_SIZE);
    return 0;
}
#else
static int patch_target(void *target, void *landing) {
    long page = sysconf(_SC_PAGESIZE);
    uintptr_t start = (uintptr_t)target & ~(uintptr_t)(page - 1);
    uintptr_t end = ((uintptr_t)target + HLMOD_JUMP_SIZE + page - 1) & ~(uintptr_t)(page - 1);
    if (mprotect((void *)start, end - start, PROT_READ | PROT_WRITE | PROT_EXEC) != 0) return -1;
    write_jump((unsigned char *)target, landing);
    mprotect((void *)start, end - start, PROT_READ | PROT_EXEC);
    return 0;
}
#endif


/* MSVC's `/INCREMENTAL` linking (the default for many Debug/RelWithDebInfo
 * configs) gives every function its own 5-byte `jmp rel32` thunk in a
 * dedicated table, so the address seen through a function pointer is the
 * thunk, not the real function body - and the thunk itself is nothing but
 * an unconditional jump, with no usable prologue at all. Also handles the
 * `jmp qword ptr [rip+disp32]` form used by cross-DLL import thunks.
 * Chases up to 8 hops (real chains are 1 deep; the bound only guards
 * against a malformed/cyclic table) to reach the actual function to hook,
 * so both thunk-mediated and any direct internal callers are intercepted. */
static void *resolve_jmp_chain(void *addr) {
    for (int hop = 0; hop < 8; hop++) {
        const unsigned char *b = (const unsigned char *)addr;
        if (b[0] == 0xE9) {
            int32_t disp;
            memcpy(&disp, b + 1, 4);
            addr = (void *)(b + 5 + disp);
            continue;
        }
        if (b[0] == 0xFF && b[1] == 0x25) {
            int32_t disp;
            memcpy(&disp, b + 2, 4);
            void *const *slot = (void *const *)(b + 6 + disp);
            addr = *slot;
            continue;
        }
        break;
    }
    return addr;
}

int hlmod_native_hook_ensure_installed(int findex, hl_type *signature) {
    InstalledNativeHook *existing;
    HASH_FIND_INT(g_installed_native_hooks, &findex, existing);
    if (existing) return 0;

    void *target = g_module->functions_ptrs[findex];
    if (!target) {
        PyErr_SetString(PyExc_RuntimeError, "This native has not been resolved yet");
        return -1;
    }
    target = resolve_jmp_chain(target);
    int reloc_offsets[HLMOD_MAX_RELOCATIONS], reloc_count = 0;
    int safe_len = safe_prologue_len_ex((const unsigned char *)target, HLMOD_JUMP_SIZE, reloc_offsets, HLMOD_MAX_RELOCATIONS, &reloc_count);
    if (safe_len < 0) {
        const unsigned char *b = (const unsigned char *)target;
        PyErr_Format(PyExc_RuntimeError,
            "Cannot safely hook this native: no recognizable >=%d byte prologue at its "
            "entry point (bytes: %02x %02x %02x %02x %02x %02x %02x %02x)",
            HLMOD_JUMP_SIZE, b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7]);
        return -1;
    }

#if defined(HL_WIN)
    /* Unlike the landing stub (fixed shape, unwind info hand-built below),
     * `resume` is an arbitrary copy of this specific native's own prologue
     * bytes. A `call rel32` in there (typically a `__chkstk` stack probe
     * for natives with large locals) means `resume` briefly becomes a
     * genuine non-leaf frame with no way to describe its unwind info
     * generically. Left unguarded this is the same failure mode as the
     * landing stub fixed below: fine until an exception needs to unwind
     * through it, then STATUS_BAD_FUNCTION_TABLE takes the whole process
     * down. Refuse rather than risk it. */
    if (reloc_count > 0) {
        PyErr_SetString(PyExc_RuntimeError,
            "Cannot safely hook this native on Windows: its prologue contains a call "
            "(e.g. a stack probe) that would need its own unwind metadata once copied "
            "into the resume trampoline, and hlmod cannot hand-build accurate unwind "
            "info for an arbitrary copied prologue the way it can for its own fixed-shape "
            "landing stub");
        return -1;
    }
#endif

    void *resume = hl_alloc_executable_memory(safe_len + HLMOD_JUMP_SIZE);
    if (!resume) {
        PyErr_NoMemory();
        return -1;
    }
    memcpy(resume, target, safe_len);
    /* `call rel32`'s displacement is relative to its own address, which
     * differs between `target` and `resume`; recompute it so the copied
     * call still reaches the exact same absolute destination. */
    for (int i = 0; i < reloc_count; i++) {
        int off = reloc_offsets[i];
        int32_t old_disp;
        memcpy(&old_disp, (const unsigned char *)target + off + 1, 4);
        intptr_t call_target = (intptr_t)((const unsigned char *)target + off + 5) + old_disp;
        intptr_t new_disp_wide = call_target - (intptr_t)((unsigned char *)resume + off + 5);
        if (new_disp_wide < INT32_MIN || new_disp_wide > INT32_MAX) {
            hl_free_executable_memory(resume, safe_len + HLMOD_JUMP_SIZE);
            PyErr_SetString(PyExc_RuntimeError,
                "Cannot safely hook this native: a relocated call's target is out of 32-bit displacement range");
            return -1;
        }
        int32_t new_disp = (int32_t)new_disp_wide;
        memcpy((unsigned char *)resume + off + 1, &new_disp, 4);
    }
    write_jump((unsigned char *)resume + safe_len, (unsigned char *)target + safe_len);

    HlmodNativeHookCtx *hookctx = malloc(sizeof(HlmodNativeHookCtx));
    if (!hookctx) {
        hl_free_executable_memory(resume, safe_len + HLMOD_JUMP_SIZE);
        PyErr_NoMemory();
        return -1;
    }
    hookctx->findex = findex;
    hookctx->original = resume;

    int codesize = 0;
    void *landing = hl_jit_native_hook_adapter(signature, hookctx, &codesize);
    if (!landing) {
        free(hookctx);
        hl_free_executable_memory(resume, safe_len + HLMOD_JUMP_SIZE);
        PyErr_NoMemory();
        return -1;
    }
#if defined(HL_WIN)
    register_landing_unwind_info(landing, codesize);
#endif

    if (patch_target(target, landing) != 0) {
        free(hookctx);
        hl_free_executable_memory(resume, safe_len + HLMOD_JUMP_SIZE);
        hl_free_executable_memory(landing, codesize);
        PyErr_SetString(PyExc_RuntimeError,
            "Failed to make the native function's memory page writable for hooking");
        return -1;
    }

    InstalledNativeHook *record = malloc(sizeof(InstalledNativeHook));
    if (record) {
        record->findex = findex;
        record->landing = landing;
        HASH_ADD_INT(g_installed_native_hooks, findex, record);
    }
    return 0;
}

#else /* !HL_64 || HL_CONSOLE */

int hlmod_native_hook_ensure_installed(int findex, hl_type *signature) {
    (void)findex;
    (void)signature;
    PyErr_SetString(PyExc_RuntimeError, "Native hooking requires an x86-64 build of hlmod");
    return -1;
}

#endif

PyObject *hlmod_py_native_findex(PyObject *self, PyObject *args) {
    const char *lib, *name;
    if (!PyArg_ParseTuple(args, "ss", &lib, &name)) return NULL;
    if (!g_module || !g_module->code) {
        PyErr_SetString(PyExc_RuntimeError, "hlmod is not initialized.");
        return NULL;
    }
    hl_code *code = g_module->code;
    for (int i = 0; i < code->nnatives; i++) {
        hl_native *n = &code->natives[i];
        if (strcmp(n->lib, lib) == 0 && strcmp(n->name, name) == 0) {
            return PyLong_FromLong(n->findex);
        }
    }
    PyErr_Format(PyExc_KeyError, "No native \"%s@%s\" in the loaded bytecode", lib, name);
    return NULL;
}

/* Testing/debugging hook: runs the same prologue decoder used by
 * `hlmod_native_hook_ensure_installed` over an arbitrary caller-supplied
 * buffer, returning the decoded length or -1 if the buffer starts with an
 * unrecognized or control-flow instruction. `buf` must contain at least
 * `min_len + 16` trailing bytes so the decoder's own runaway guard can never
 * read past the end of the buffer while decoding the instruction that
 * crosses `min_len`. */
PyObject *hlmod_py_native_hook_test_prologue(PyObject *self, PyObject *args) {
    const char *buf;
    Py_ssize_t buflen;
    int min_len;
    if (!PyArg_ParseTuple(args, "y#i", &buf, &buflen, &min_len)) return NULL;
    if (min_len < 0 || (Py_ssize_t)min_len + 16 > buflen) {
        PyErr_SetString(PyExc_ValueError, "buf must have at least min_len + 16 bytes");
        return NULL;
    }
#if defined(HL_64) && !defined(HL_CONSOLE)
    return PyLong_FromLong(safe_prologue_len((const unsigned char *)buf, min_len));
#else
    PyErr_SetString(PyExc_RuntimeError, "Native hook prologue decoding requires an x86-64 build of hlmod");
    return NULL;
#endif
}
